package main

// Все фотографии постов. Имя файла говорит, что на нём, — по нему пост
// в demo/stories/000-dacha/seed.sql и подбирает подпись.

func photos() []Pic {
	const (
		L, S, P = 1600, 1400, 1200 // альбомная, квадратная, портретная
	)
	return []Pic{
		photo("cucumbers-1", P, L, cucumbers, 0),
		photo("cucumbers-2", L, P, cucumbers, 1),
		photo("greenhouse-1", L, 1067, greenhouse, 0),
		photo("greenhouse-2", L, P, greenhouse, 1),
		photo("compost-1", L, P, compost, 0),
		photo("tomatoes-1", L, P, tomatoes, 0),
		photo("tomatoes-2", S, S, tomatoes, 1),
		photo("tomatoes-3", L, 1067, tomatoes, 2),
		photo("tomatoes-4", L, P, tomatoes, 3),
		photo("tomatoes-5", P, L, tomatoes, 4),
		photo("tomatoes-6", S, S, tomatoes, 5),
		photo("tomatoes-7", P, L, tomatoes, 6),
		photo("raspberry-1", P, L, raspberry, 0),
		photo("raspberry-2", S, S, raspberry, 1),
		photo("strawberry-1", L, P, strawberry, 0),
		photo("strawberry-2", L, 1067, strawberry, 1),
		photo("strawberry-3", P, L, strawberry, 2),
		photo("street-1", L, 1067, street, 0),
		photo("street-2", L, P, street, 1),
		photo("street-3", L, P, street, 2),
		photo("street-4", L, 900, street, 3),
		photo("jars-1", L, P, jars, 0),
		photo("jars-2", L, 1067, jars, 1),
		photo("jars-3", P, L, jars, 2),
		photo("jars-4", S, S, jars, 3),
		photo("jars-5", P, L, jars, 4),
		photo("hives-1", L, 1067, hives, 0),
		photo("hives-2", L, P, hives, 1),
		photo("hives-3", P, L, hives, 2),
		photo("apples-1", P, L, apples, 0),
		photo("apples-2", L, P, apples, 1),
		photo("apples-3", L, 1067, apples, 2),
		photo("apples-4", S, S, apples, 3),
		photo("lake-1", L, 900, lake, 0),
		photo("lake-2", L, 1067, lake, 1),
		photo("dahlias-1", L, P, dahlias, 0),
		photo("dahlias-2", P, L, dahlias, 1),
		photo("potato-1", L, P, potato, 0),
		photo("potato-2", S, S, potato, 1),
		photo("potato-3", L, 1067, potato, 2),
		photo("potato-4", L, P, potato, 3),
		photo("flowerbed-1", L, P, flowerbed, 0),
		photo("flowerbed-2", P, L, flowerbed, 1),
		photo("flowerbed-3", P, L, flowerbed, 2),
		photo("banya-1", L, 1067, banya, 0),
		photo("banya-2", S, S, banya, 1),
		photo("pumpkin-1", L, P, pumpkin, 0),
		photo("pumpkin-2", L, 1067, pumpkin, 1),
		photo("peppers-1", P, L, peppers, 0),
		photo("peppers-2", L, P, peppers, 1),
		photo("zucchini-1", L, P, zucchini, 0),
		photo("zucchini-2", L, 1067, zucchini, 1),
		photo("sunflowers-1", P, L, sunflowers, 0),
		photo("sunflowers-2", L, P, sunflowers, 1),
		photo("carrots-1", L, P, carrots, 0),
		photo("bonfire-1", L, 1067, bonfire, 0),
		photo("roses-1", L, P, roses, 0),
		photo("mushrooms-1", L, P, mushrooms, 0),
		photo("mushrooms-2", S, S, mushrooms, 1),
		photo("cat-1", P, L, cat, 0),
		photo("herbs-1", P, L, herbs, 0),
		photo("house-1", L, 1067, house, 0),
		photo("house-2", L, P, house, 1),
		photo("beets-1", L, P, beets, 0),
		photo("cabbage-1", L, P, cabbage, 0),
		photo("cabbage-2", L, 1067, cabbage, 1),
		photo("beds-1", L, P, beds, 0),
		photo("beds-2", L, 1067, beds, 1),
		photo("beds-3", L, P, beds, 2),
		photo("currants-1", L, P, currants, 0),
		photo("cherries-1", P, L, cherries, 0),
		photo("peonies-1", L, P, peonies, 0),
		photo("peonies-2", S, S, peonies, 1),
		photo("blossom-1", L, 1067, blossom, 0),
		photo("blossom-2", P, L, blossom, 1),
		photo("blossom-3", L, P, blossom, 2),
		photo("tulips-1", P, L, tulips, 0),
		photo("seedlings-1", L, P, seedlings, 0),
		photo("seedlings-2", S, S, seedlings, 1),
		photo("winter-1", L, 1067, winter, 0),
		photo("field-1", L, 900, field, 0),
	}
}
